import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "./_components/AppSidebar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { clerkAppearance } from "@/lib/clerk-appearance";
import { LibraryProvider } from "./context/LibraryContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={clerkAppearance}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <SidebarProvider defaultOpen={true}>
             <LibraryProvider>

                    <AppSidebar />

            {/* Wrapper so the trigger + page content stack vertically */}
            <div className="flex flex-col flex-1 min-w-0 overflow-hidden">

              <Provider >
               
                  {children}
                
              </Provider>
            </div>
             </LibraryProvider>
        
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
